[package]
description = "Parser for the TLS protocol"
license = "LGPL-2.1+"
keywords = ["TLS","SSL","protocol","parser","nom"]
homepage = "https://github.com/rusticata/tls-parser"
repository = "https://github.com/rusticata/tls-parser.git"
name = "tls-parser"
version = "0.3.0"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]
build = "build.rs"

[lib]
name = "tls_parser"

[features]
default = []
serialize = []

[dependencies]
nom = {version = "^2", features=["verbose-errors"] }
phf = "0.7.16"
enum_primitive = "0.1.0"
rusticata-macros = "*"

# [dependencies.rusticata-macros]
# path = "../rusticata-macros"

[build-dependencies]
phf_codegen = "0.7.16"
