[package]
description = "Parser for the TLS protocol"
license = "LGPL-2.1+"
keywords = ["TLS","SSL","protocol","parser","nom"]
homepage = "https://github.com/rusticata/tls-parser"
repository = "https://github.com/rusticata/tls-parser.git"
documentation = "https://docs.rs/tls-parser"
name = "tls-parser"
version = "0.4.0"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]
categories = ["parsing"]
build = "build.rs"

[lib]
name = "tls_parser"

[dependencies]
nom = {version = "^2.0", features=["verbose-errors"] }
phf = "0.7.16"
enum_primitive = "^0.1"
rusticata-macros = "^0"

[build-dependencies]
phf_codegen = "0.7.16"

[badges]
travis-ci = { repository = "rusticata/tls-parser" }
